### ISSUE TITLE
vlc: Play ID did not longer work with companion 2.1.1

### ISSUE THREAD

**Issue by X21de** [bitfocus/companion-module-videolan-vlc#18]
With the Version 2.1.1 the vlc function Play ID did not work.
Nothing happened when I press the button with e.g. Play ID 4
Play, Pause, Stop and the color responses works fine.

With companion Version 2.0.1-2660 it worked fine. 

Working on a Mac 10.15.7 with VLC 3.0.11.1

ps: The new functions with the remaining time of a file did not work ether.

**Comment by istnv** [comment]
Pull request #16 fixes this.

**Comment by mades5** [comment]
Is this version live yet? Today I installed the VLC module on Companion 2.1.1 and the buttons with Play ID do not work. Play and pause, however, do.
I have created a playlist with 10 entries and when I display the list of dynamic variables, I see the VLC version 3.0.11.1 and the play status correctly, r_id always remains at -1, r_name empty and all other variables at 0.
Any news on this?

**Comment by istnv** [comment]
The issue you describe is fixed in the recent 2.2.0 builds. The module used to use the "Playlist" section of the VLC response, but VLC localizes the internals (German returns "Wiedergabaliste" which doesn't match). A workaround for earlier modules is to force the interface language to 'English' under Preferences.
