### ISSUE TITLE
VLC Play Specific PlayList Item ID

### ISSUE THREAD

**Issue by rmdoprado** [bitfocus/companion-module-videolan-vlc#3]
**Describe the feature**
I would like to request a option to play a specific playlist item ID. We should be able to input the ID number of the playlist item in order to play it.

**Is this platform dependent (windows, mac, ..)?**
Not Applicable
**If documentation is required to implement, do you know where to find it?**
https://wiki.videolan.org/VLC_HTTP_requests/

Command mentioned on the website.
?command=pl_play&id=<id>

**Usecases**
The user can have a long playlist on VLC, and it should be able to select what item it should be played using the Item ID.

**Comment by scoobiekw** [comment]
I did. IDs start at 3 and are in order added to playlist..fancy version of module with clip names in gestation

**Comment by rmdoprado** [comment]
> I did. IDs start at 3 and are in order added to playlist..fancy version of module with clip names in gestation

Did you manage to submit the code? I was not able to see it on the latest beta version.

**Comment by McHauge** [comment]
@rodrigomarcondess and @scoobiekw Sorry about the delay on the merge just saw it now, it should be merged into the module now will poke one of the core devs to update the module in the core. After that, it should be available in the V2.0 builds

**Comment by XaviMM** [comment]
> 
> fancy version of module with clip names in gestation

Any news regarding that?

**Comment by KOHPM** [comment]
> > fancy version of module with clip names in gestation
> 
> Any news regarding that?


ok, digging a little further I found this: 

I saved my playlist as a xspf file. and opened it with text editor 

```
<?xml version="1.0" encoding="UTF-8"?>
<playlist xmlns="http://xspf.org/ns/0/" xmlns:vlc="http://www.videolan.org/vlc/playlist/ns/0/" version="1">
	<title>Playlist</title>
	<trackList>
		<track>
			<location>file:///Users/kohp/Library/Mobile%20Documents/com~apple~TextEdit/Documents/videos/OFF%20AIR.mp4</location>
			<title>OFF AIR</title>
			<image>file:///Users/kohp/Library/Caches/org.videolan.vlc/art/arturl/61dea298b90d13c677b25829eb5996c0/art.jpg</image>
			<duration>16716</duration>
			<extension application="http://www.videolan.org/vlc/playlist/0">
				<vlc:id>0</vlc:id>
			</extension>
		</track>
		<track>
			<location>file:///Users/kohp/Library/Mobile%20Documents/com~apple~TextEdit/Documents/videos/ON%20AIR.mov</location>
			<title>ON AIR</title>
			<trackNum>2</trackNum>
			<image>file:///Users/kohp/Library/Caches/org.videolan.vlc/art/arturl/b4c12c0b292d660602011dceaf0701cb/art.jpg</image>
			<duration>66120</duration>
			<extension application="http://www.videolan.org/vlc/playlist/0">
				<vlc:id>1</vlc:id>
			</extension>
		</track>
		<track>
			<location>file:///Users/kohp/Library/Mobile%20Documents/com~apple~TextEdit/Documents/videos/TIMER.m4a</location>
			<title>TIMER</title>
			<image>file:///Users/kohp/Library/Caches/org.videolan.vlc/art/arturl/61dea298b90d13c677b25829eb5996c0/art.jpg</image>
			<duration>30859</duration>
			<extension application="http://www.videolan.org/vlc/playlist/0">
				<vlc:id>2</vlc:id>
			</extension>
		</track>
	</trackList>
	<extension application="http://www.videolan.org/vlc/playlist/0">
			<vlc:item tid="0"/>
			<vlc:item tid="1"/>
			<vlc:item tid="2"/>
	</extension>
</playlist>

```

and I have set my button to play as following 

OFF AIR = id = 0 = Play ID/Clip Nr. 3
ON AIR = id = 1 = Play ID/Clip Nr. 5
TIMER = id 2 = Play ID/Clip Nr. 4

can't explain the logic of this thing!

but if it could help, that's how I figured out. I have also switched around the order of the playlist files. till i got it right. 

I have suspected we were to add +2 on each, but did not work for me.

**Comment by istnv** [comment]
I took a look at this problem.
Apparently, most VLC remote control commands expect an internal 'Media ID' which does not always correspond to the ID column in the playlist window. This 'Media ID' is not easily located and can also change internally. When sending the 'play' command to VLC, the HTTP interface expects this internal 'Media ID'.

The internal ID #1 is always then entire 'Playlist', and ID #2 is the entire 'Media library'. 

A fresh loaded playlist *should* start at ID #3, which is where the +2 solution sometimes works.
But if you clear the playlist then re-load, the Media IDs start from where they left off the first time.

In order to reliably start a specific item, the module will need to be re-factored to use a different control interface that uses the displayed Playlist ID or manage the playlist internally (VLC does respond to a playlist request in display order).

**Comment by KOHPM** [comment]
Thanks. Yes toi time also to dig see. And yes you're right. What we ended up doing is that the ID we wanna play, we just keep increasing the # into the Companion dashboard till it plays the right one. So if we have 3 item in the playlist this should have given us normally 2, 3, 4. Because the internal I'd shows 0,1,2. But won't work. So you're right if we start with 3 it plays something, then we will think okay we at now 4 and 5... but won't work. So what we do, if we wanna play second item in playlist we just keep increasing on the Play ID number and sometimes we get it to play at 9 and the third at 6.So we left with this bizarre work around. But is there a way to send command to iTunes (now called Music) on Mac ?Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: John Knight Jr <notifications@github.com> Date: 10/24/20  10:42 PM  (GMT-05:00) To: bitfocus/companion-module-videolan-vlc <companion-module-videolan-vlc@noreply.github.com> Cc: KOHPM <kingdom@kohpministries.com>, Comment <comment@noreply.github.com> Subject: Re: [bitfocus/companion-module-videolan-vlc] VLC Play Specific PlayList Item ID (#3) 
I took a look at this problem.
Apparently, most VLC remote control commands expect an internal 'Media ID' which does not always correspond to the ID column in the playlist window. This 'Media ID' is not easily located and can also change internally. When sending the 'play' command to VLC, the HTTP interface expects this internal 'Media ID'.
The internal ID #1 is always then entire 'Playlist', and ID #2 is the entire 'Media library'.
A fresh loaded playlist should start at ID #3, which is where the +2 solution sometimes works.
But if you clear the playlist then re-load, the Media IDs start from where they left off the first time.
In order to reliably start a specific item, the module will need to be re-factored to use a different control interface that uses the displayed Playlist ID or manage the playlist internally (VLC does respond to a playlist request in display order).

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/bitfocus/companion-module-videolan-vlc/issues/3#issuecomment-716084688",
"url": "https://github.com/bitfocus/companion-module-videolan-vlc/issues/3#issuecomment-716084688",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
