### ISSUE TITLE
[BUG] VLC plugin / play ID command not working anymore

### ISSUE THREAD

**Issue by nils-maker** [bitfocus/companion-module-videolan-vlc#44]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi guys, previously I was running a 2.2.0 RC / beta version from April 2021 on Windows 10 - everything was running stable and smooth, the "play ID" command of VLC module was working 100% reliable and smooth. 

Last week I installed the lastest official release 2.1.4 and noticed that VLC "play ID" command is not working anymore. No errors, just the fact that nothing happens if the command is triggered. 

I then downloaded the latest 2.2.0 RC2 and also in this version the "play ID" command for VLC is not working anymore.  So I ended up in "downgrading" to the 2.2.0 RC from April 2021 and everything is working again. 

I tried to access VLC via browser using http://127.0.0.1:8080 address - it's accessible in all companion versions I have tried out. So I think the problem might not be located in the VLC module. 

### Steps To Reproduce

1. Install and setup VLC module with either latest RC2 or latest official companion build
2. Create new button with action "vlc: Play ID" 
3.  Open VLC player with playlist (make sure ID from step 2 exists in playlist)
4. Press "Test actions" button and see that nothing happens

### Environment (please complete the following information)

```markdown
- OS: Windows 10
- Browser: Chrome 99
- Companion Version: 2.1.4-b03d4f0f
```

**Comment by JeffreyDavidsz** [comment]
Did you read the help in the module?

**Comment by JeffreyDavidsz** [comment]
IMPORTANT UPDATE!

If you used this module prior to the feedback and variables version, the Play ID has changed! The prior versions sometimes worked by starting the playlist at number 3. This version retrieves the current playlist from VLC and numbers from 1 at the top.The first item in the list is always number 1 which means if you click the heading and sort the list, number 1 is still the first one on the list.

VLC does not generate an error if you enter a Play ID that is not in the playlist. It will play the active item as if the Play ID was not there.

Due to the nature of the feedback and play list syncronization, the module status shows ERROR if VLC is not running yet. This is normal. It is to let you know that buttons may not work as expected. The status will automatically change to OK when you start VLC.

**Comment by nils-maker** [comment]
Hey @JeffreyDavidsz , thanks for your comment. Yes, I read the help and got that point with the playlist ID. I have a playlist with approx. 40 videos and if I start the video with ID 20 at least one video in the playlist should be played, I guess ;-) 

Besides from that the same help text of the VLC module is already displayed in 2.2.0 RC from April 2021 so obviously that was already implemented in that version.

**Comment by JeffreyDavidsz** [comment]
Ok I haven't checked it further but the command seems valid, so need to check the API

**Comment by istnv** [comment]
Looking over the module, nothing but cosmetic changes to the module since last August

**Comment by nils-maker** [comment]
@JeffreyDavidsz Thanks for your help! 

@istnv  Okay, I only checked the function with version 2.2.0 RC from April 2021 and with official built from this January, nothing in between - unfortunately.

**Comment by istnv** [comment]
Closing. No comment for over a year.
