### ISSUE TITLE
VLC Module causes 100% CPU Load on large Playlists (RPi4)

### ISSUE THREAD

**Issue by DJSpyman** [bitfocus/companion-module-videolan-vlc#74]
Hello Everyone,

I tracked down an issue with large playlists on raspberry pi.
I have a playlist with roughly 50000 mp3 files. It is a 25MB playlist file !

Whenever I connect the module with my running (and playing) VLC instance the  VLC cpu usage spikes to 100%

Therefore VLC comes unresponsive on "next,play,pause,etc..."

I checked the sourcecode and suggest it comes from the 
```
pollPlaylist() {
		// don't ask until connected (we have a valid status response)
		if (this.lastStatus == InstanceStatus.Ok) {
			this.getRequest('/requests/playlist.json', this.updatePlaylist.bind(this))
		}
	}
```
function as it polls every 500ms ! 
```
	startup() {
		this.stopTimers()

		this.reset_variables()

		if (this.config.host && this.config.port) {
			this.updateStatus(InstanceStatus.Connecting)

			this.baseURL = `http://${this.config.host}:${this.config.port}`
			this.headers = {}

			if (this.config.password) {
				this.headers = {
					Authorization: 'Basic ' + Buffer.from(`:${this.config.password}`).toString('base64'),
				}
			}

	---->		this.plPoll = setInterval(() => this.pollPlaylist(), 500)      <---
			this.pbPoll = setInterval(() => this.pollPlayback(), 10)
		} else {
			this.updateStatus(InstanceStatus.BadConfig)
		}
	}
```

It is a shame I couldn't evaluate further as the code is obfuscated in my companion instance.

**Comment by DJSpyman** [comment]
by the way I just recently updated my companionpi version. I have the exact same setup running vlc module 1.0.2 without any problems.

**Comment by DJSpyman** [comment]
accidentally closed issue *facepalm*

**Comment by DJSpyman** [comment]
confirmed: I set the poll timer to 50000 (in the obfuscated code 🔢 ) and the module runs smoothly 
(effect: every 50 seconds a get a short cpu spike for a few seconds)

**Comment by istnv** [comment]
The code isn't obfuscated. All excess whitespace is removed for size. Obfuscated would change all of the variable names to garbage. It is nicely formatted in the repository.

If you don't alter the playlist very much, increasing the timer works. 

VLC does not offer a 'subscription' to alert Companion when the playlist has changed which is why it Polls. 
If the timing is too large, the playlist gets out of sync if it is being modified in VLC. You could change items and hit play on companion before sync. Then the wrong item plays.

I have not found a way to ask for parts of the playlist, either.

I could add an option to disable that particular polling and create a 'refresh list' action to put on a button.

**Comment by istnv** [comment]
I've adjusted the polling frequency to automatically fall back to every 15 seconds while VLC is actually playing. If that is still too much load, I'll look at a way of disabling it.
